# Generated by Django 5.0.1 on 2024-03-09 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='shop_contact',
            field=models.CharField(max_length=20),
        ),
    ]
