# Generated by Django 5.0.1 on 2024-03-09 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_product_shop_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='contact',
            field=models.CharField(help_text='Enter the contact number with the country code e.g: +254712345678.', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='shop_contact',
            field=models.CharField(max_length=20),
        ),
    ]
