# Generated by Django 5.0.1 on 2024-03-10 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_order_contact_alter_order_shop_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='shop',
        ),
        migrations.AddField(
            model_name='product',
            name='mass',
            field=models.CharField(choices=[('6kg', 'Small - 6kg'), ('13kg', 'Medium - 13kg'), ('26kg', 'Large - 26kg')], default='6kg', max_length=100),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Delivery',
        ),
    ]
