# Generated by Django 5.0.1 on 2024-01-15 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='mass',
            field=models.CharField(blank=True, choices=[('small', 'Small - 6kg'), ('medium', 'Medium - 13kg'), ('large', 'Large - 26kg')], max_length=100, null=True),
        ),
    ]
