# Generated by Django 5.0.1 on 2024-03-07 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='location',
            field=models.CharField(default=710584581, max_length=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='contact',
            field=models.BigIntegerField(),
        ),
    ]
