# Generated by Django 5.0.1 on 2024-03-07 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_remove_order_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='contact',
            field=models.BigIntegerField(default=710584581),
            preserve_default=False,
        ),
    ]
