# Generated by Django 5.0.1 on 2024-03-08 09:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_order_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='user',
            new_name='created_by',
        ),
        migrations.AddField(
            model_name='order',
            name='shop_contact',
            field=models.ForeignKey(default=710584581, on_delete=django.db.models.deletion.CASCADE, related_name='orders_related_to_shop_contact', to='shop.product'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders_related_to_product', to='shop.product'),
        ),
    ]
