# Generated by Django 5.0.1 on 2024-03-08 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_rename_user_order_created_by_order_shop_contact_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
    ]
